### ISSUE TITLE
Galera can never be Ready

### ISSUE THREAD

**Issue by Quentin-M** [stackanetes/stackanetes#100]
Hi,

I am having trouble understanding how Galera, merged recently with PR #90, can ever become Ready. The first thing that [`start.sh`](https://github.com/stackanetes/stackanetes/blob/f65c67d/mariadb/templates/configmaps/start.sh.yaml.j2#L21) does is running [`peer-finder.py`](https://github.com/stackanetes/stackanetes/blob/f65c67d/mariadb/templates/configmaps/peer-finder.py.yaml.j2), which tries to get service endpoints for MariaDB and loop if it can't. However, the daemonset has a `readinessProbe` that won't mark the pods as _Ready_ until the kubelet can establish a TCP connection to MariaDB, which can't happen until `peer-finder.py` finishes.

Also, it [seems](https://github.com/stackanetes/stackanetes/blob/f65c67d/mariadb/templates/configmaps/peer-finder.py.yaml.j2#L66) that at soon as it gets an endpoint which isn't the local IP address, it ends. What happens if the first replica is there, but my second replica is still being created and will only be up in 30 seconds? Shouldn't it wait for the required number of replicas?

Another remark, the result of `get_my_ip_address()` should probably be cached, no reason to create useless load on a loop.

Thanks.

**Comment by Quentin-M** [comment]
@mateusz-blaszkowski

**Comment by mateusz-blaszkowski** [comment]
Hi,

Alongside with the DaemonSet, there is a new `mariadb-init` job. It's purpose is to be the first MariaDB instance that is created with the `--wsrep_new_cluster` parameter. Instances from the DaemonSet are supposed to join the cluster (started by the Job, thus the first endpoint should appear) with `--wsrep_cluster_address` parameter set to the IP address of the Job's instance. The job, after starting the MariaDB instance, periodically checks `wsrep_cluster_size`. If it's set to (replicas + 1), it waits for the cluster to be in a `Synced` state and then completes. For example, when the number of replicas is set to 3, exactly one mariadb-init pod and three mariadb pods should be created. The job completes when all three instances created by the DaemonSet joins the cluster (`wsrep_cluster_size` is set to 4 and `wsrep_local_state_comment` is set to `Synced`). This desired auto-clustering couldn't be accomplished without the Job because the DaemonSet MariaDB instances couldn't identify which one of them should be the seed instance (seed needs to start the cluster using `--wsrep_new_cluster`). 

The scenario is a little different when the user requests to build only one instance (`replicas=1`). In such case, the Job is started but exists [immediately](https://github.com/mateusz-blaszkowski/stackanetes/blob/12f7897f8089212ce27ffaa426129530c9d35df8/mariadb/templates/configmaps/seed.sh.yaml.j2#L66). Single DaemonSet instance doesn't need to join the cluster and simply builds the target one.

**Comment by Quentin-M** [comment]
Thanks for your answer. I didn't pay attention to the `mariadb-init` job yesterday, it was hidden in the completed objects section. It appears that the job eventually marked itself as completed even though every attempts failed. Checking at his logs today revealed that the `boostrap-db.sh` was erroneous on rkt. I pushed a small fix and it now progresses.

All pods have joined, they all show `wsrep_cluster_size=3`, `wsrep_local_state_comment=Synced`. However, the init job won't finish because it still shows `wsrep_cluster_size=1`. Have you seen that before?

**Comment by Quentin-M** [comment]
Noticed the `wsrep_cluster_state_uuid` is different between the pods and the init job, which explains why the size can be different.

**Comment by Quentin-M** [comment]
Latest attempt worked fine with https://github.com/stackanetes/stackanetes/commit/616add869585b199815cff0a02cb481efa20c795 and https://github.com/stackanetes/stackanetes/commit/c28979e58012adb7f9e9e567d0570c619a6b0e9c. Closing.
